Repository thirionlogan/amazonia, pull requests merged in 2020-12, with the labels that each got.

#11 Initial express server Closes #3
  README.md
  config/env.js
  config/getHttpsConfig.js
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/modules.js
  config/paths.js
  config/pnpTs.js
  config/webpack.config.js
  config/webpackDevServer.config.js
  package-lock.json
  package.json
  scripts/build.js
  scripts/start.js
  scripts/test.js
  server/app.js
  server/app.test.js
  server/server.js
Labels: enhancement

#19 add test coverage requirements to jest tests
  package.json
Labels: enhancement

#20 Database initial closing #4 #18
  .env.example
  README.md
  package-lock.json
  package.json
  server/app/app.js
  server/app/app.test.js
  server/data/db.js
  server/data/migrations/20201218102915_add_wishlist_table.js
  server/data/migrations/20201218103743_add_item_table.js
  server/data/seeds/001_seed_wishlist.js
  server/data/seeds/002_seed_item.js
  server/knexfile.js
  server/server.js
Labels: enhancement

#29 update schema
  schema.png
Labels: documentation

#39 Wishlist editor
  README.md
  package-lock.json
  package.json
  server/app/app.js
  src/components/App/App.css
  src/components/App/App.js
  src/components/WishlistEditor/WishlistEditor.css
  src/components/WishlistEditor/WishlistEditor.js
  src/components/WishlistEditor/WishlistEditor.test.js
  src/setupTests.js
Labels: enhancement

#48 Patch delete
  server/app/app.js
  server/app/app.test.js
Labels: enhancement

#50 fix database seed bug
  package.json
Labels: bug

#52 #9 implement add button
  package-lock.json
  package.json
  src/components/App/App.js
  src/components/App/App.test.js
  src/components/HomePage/HomePage.js
  src/components/HomePage/HomePage.test.js
Labels: enhancement

#53 #32 implement delete button
  src/client/client.js
  src/components/HomePage/HomePage.js
  src/components/HomePage/HomePage.test.js
  src/components/Wishlist/Wishlist.js
  src/components/Wishlist/Wishlist.test.js
  src/mocks/handlers.js
Labels: enhancement
